import type { Binding, Op, Skill, Target } from "./types";

export const TARGETS: Target[] = [
  {
    id: "t-claude-home",
    agent: "claude",
    profile: "home",
    path: "~/.claude/skills",
    ownership: "observed",
    skills: 18,
    lastSync: "12 min ago",
  },
  {
    id: "t-claude-work",
    agent: "claude",
    profile: "work",
    path: "~/.claude-work/skills",
    ownership: "managed",
    skills: 24,
    lastSync: "1 min ago",
  },
  {
    id: "t-codex-home",
    agent: "codex",
    profile: "home",
    path: "~/.codex/skills",
    ownership: "observed",
    skills: 14,
    lastSync: "4 min ago",
  },
  {
    id: "t-cursor-home",
    agent: "cursor",
    profile: "home",
    path: "~/.cursor/skills",
    ownership: "managed",
    skills: 9,
    lastSync: "2 min ago",
  },
  {
    id: "t-windsurf",
    agent: "windsurf",
    profile: "home",
    path: "~/.windsurf/skills",
    ownership: "external",
    skills: 6,
    lastSync: "n/a",
  },
  {
    id: "t-repo-claude",
    agent: "claude",
    profile: "repo",
    path: "/repo/.claude/skills",
    ownership: "managed",
    skills: 11,
    lastSync: "8 min ago",
  },
];

export const SKILLS: Skill[] = [
  {
    id: "s-refactor",
    name: "refactor-patterns",
    tag: "rust",
    version: "v0.4.2",
    captures: 12,
    released: "v0.4",
    changed: "2d",
    targets: ["t-claude-home", "t-claude-work", "t-codex-home", "t-cursor-home"],
  },
  {
    id: "s-commit",
    name: "commit-message-writer",
    tag: "git",
    version: "v1.2.0",
    captures: 8,
    released: "v1.2",
    changed: "5h",
    targets: [
      "t-claude-home",
      "t-claude-work",
      "t-codex-home",
      "t-cursor-home",
      "t-windsurf",
      "t-repo-claude",
    ],
  },
  {
    id: "s-pr-review",
    name: "pr-review-checklist",
    tag: "workflow",
    version: "v0.9.1",
    captures: 5,
    released: "v0.9",
    changed: "1d",
    targets: ["t-claude-work", "t-repo-claude"],
  },
  {
    id: "s-sql-audit",
    name: "sql-schema-audit",
    tag: "database",
    version: "v0.3.0",
    captures: 3,
    released: "v0.3",
    changed: "3d",
    targets: ["t-claude-home", "t-claude-work"],
  },
  {
    id: "s-rust-test",
    name: "rust-test-harness",
    tag: "rust",
    version: "v0.2.1",
    captures: 7,
    released: "v0.2",
    changed: "1d",
    targets: ["t-claude-work", "t-codex-home", "t-repo-claude"],
  },
  {
    id: "s-typed-api",
    name: "typed-api-client",
    tag: "typescript",
    version: "v0.5.0",
    captures: 9,
    released: "v0.5",
    changed: "6h",
    targets: ["t-claude-work", "t-codex-home", "t-cursor-home"],
  },
  {
    id: "s-debug-tui",
    name: "debug-narrator",
    tag: "tool",
    version: "v0.1.4",
    captures: 4,
    released: "—",
    changed: "12h",
    targets: ["t-claude-home"],
  },
  {
    id: "s-onboard",
    name: "repo-onboarding",
    tag: "docs",
    version: "v0.6.0",
    captures: 6,
    released: "v0.6",
    changed: "4d",
    targets: ["t-claude-work", "t-repo-claude", "t-cursor-home"],
  },
];

export const OPS: Op[] = [
  {
    id: "op-4a21",
    status: "pending",
    kind: "project",
    skill: "refactor-patterns@v0.4.2",
    target: "claude/work",
    method: "symlink",
    time: "now",
  },
  { id: "op-4a20", status: "ok", kind: "capture", skill: "commit-message-writer", target: "—", method: "—", time: "5m ago" },
  {
    id: "op-4a1f",
    status: "ok",
    kind: "project",
    skill: "typed-api-client@v0.5.0",
    target: "cursor/home",
    method: "copy",
    time: "14m ago",
  },
  {
    id: "op-4a1e",
    status: "err",
    kind: "project",
    skill: "sql-schema-audit@v0.3.0",
    target: "windsurf/home",
    method: "symlink",
    time: "22m ago",
    reason: "target ownership=external; refusing to write",
  },
  { id: "op-4a1d", status: "ok", kind: "snapshot", skill: "rust-test-harness@v0.2.1", target: "—", method: "—", time: "1h ago" },
  { id: "op-4a1c", status: "ok", kind: "release", skill: "pr-review-checklist@v0.9.1", target: "—", method: "—", time: "3h ago" },
  {
    id: "op-4a1b",
    status: "ok",
    kind: "project",
    skill: "commit-message-writer@v1.2.0",
    target: "repo/claude",
    method: "materialize",
    time: "4h ago",
  },
  { id: "op-4a1a", status: "ok", kind: "sync-push", skill: "registry", target: "origin/main", method: "—", time: "6h ago" },
];

export const BINDINGS: Binding[] = [
  {
    id: "b-01",
    skill: "refactor-patterns",
    target: "t-claude-work",
    matcher: "path-prefix:/Users/me/work",
    method: "symlink",
    policy: "auto",
  },
  {
    id: "b-02",
    skill: "commit-message-writer",
    target: "t-claude-home",
    matcher: "name:*",
    method: "symlink",
    policy: "auto",
  },
  {
    id: "b-03",
    skill: "commit-message-writer",
    target: "t-repo-claude",
    matcher: "exact-path:/repo",
    method: "materialize",
    policy: "manual",
  },
  {
    id: "b-04",
    skill: "typed-api-client",
    target: "t-cursor-home",
    matcher: "path-prefix:/Users/me/frontend",
    method: "copy",
    policy: "auto",
  },
  {
    id: "b-05",
    skill: "rust-test-harness",
    target: "t-codex-home",
    matcher: "name:rust-*",
    method: "symlink",
    policy: "auto",
  },
];
